CREATE TABLE Equipo (
    id_equipo VARCHAR(2) PRIMARY KEY,
    pais_equipo VARCHAR(50) NOT NULL
);

INSERT INTO Equipo (id_equipo, pais_equipo) VALUES
('QA', 'Qatar'),
('EC', 'Ecuador'),
('SN', 'Senegal'),
('NL', 'Países Bajos'),
('GB', 'Inglaterra'),
('IR', 'Irán'),
('US', 'Estados Unidos'),
('WA', 'Gales'),
('AR', 'Argentina'),
('SA', 'Arabia Saudita'),
('MX', 'México'),
('PL', 'Polonia'),
('FR', 'Francia'),
('AU', 'Australia'),
('DK', 'Dinamarca'),
('TN', 'Túnez'),
('DE', 'Alemania'),
('JP', 'Japón'),
('ES', 'España'),
('CR', 'Costa Rica'),
('BE', 'Bélgica'),
('CA', 'Canadá'),
('HR', 'Croacia'),
('MA', 'Marruecos'),
('BR', 'Brasil'),
('RS', 'Serbia'),
('CH', 'Suiza'),
('CM', 'Camerún'),
('PT', 'Portugal'),
('GH', 'Ghana'),
('UY', 'Uruguay'),
('KR', 'Corea del Sur');
